version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: pharma-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 5ypq49gs@kA
      MYSQL_DATABASE: pharma_db
      MYSQL_USER: pharma_user
      MYSQL_PASSWORD: pharma_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - pharma-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p5ypq49gs@kA"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 30s

  # Spring Boot Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pharma-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/pharma_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 5ypq49gs@kA
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - pharma-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      timeout: 10s
      retries: 5
      interval: 30s
      start_period: 60s

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pharma-frontend
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - pharma-network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  pharma-network:
    driver: bridge 