name: Build and Deploy Spring Boot Backend to Azure

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package
        working-directory: backend

      - name: Check CR_PAT secret
        run: |
          if [ -z "${{ secrets.CR_PAT }}" ]; then
            echo "CR_PAT secret is not set. Please add it in your repository secrets."
            exit 1
          fi

      - name: Log in to GitHub Container Registry (using CR_PAT)
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: pharma-backend-app
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: backend/target/pharma-0.0.1-SNAPSHOT.jar 